### PR TITLE
Refactor to support alternate project file and copy to location for testing credentials

### PR DESCRIPTION
**Pull request by BDHernand**

### CODE REVIEW

**Comment by rolivieri** [comment]
- [ ] @BDHernand For this file https://github.com/IBM-Swift/BluePic/blob/setup_travis/.travis.yml, let's have the all the logic that pertains to iOS inside the conditional for OS X.

**Comment by rolivieri** [comment]
@BDHernand  Just reviewed the changes. Let’s do this to simplify the logic:

1) Let’s start by refactoring again the `BluePic-Testing-Credentials` repo and get rid of the parent `BluePic` folder. In other words, the `BluePic-Server`, `BluePic-iOS`, etc. folders should all be peers and exist at the root level of the repo.

2) Let’s make the `build_package.sh` script accept only 3 parameters:
- branch - This will go away but keeping it for now so you don’t have to deal with the PRs at the moment (this is one simply stays as is).
- projectBuildDir - This will be the path to the main directory of the project (i.e. $TRAVIS_BUILD_DIR)
- credentialsDir - This is the full path to the credentials repo for the project.
  For `Kitura-CouchDB`, this is -> `$TRAVIS_BUILD_DIR/Kitura-TestingCredentials/Kitura-CouchDB`. For `BluePic`, this is => `$TRAVIS_BUILD_DIR/BluePic-Testing-Credentials`.

Note there is no need for `alternate_project_folder` or `alternate_copy_location` parameters. Also, note that we are removing `build_dir` as a parameter; we no longer need it. `build_dir` is only used to invoke `install_swift_binaries.sh`. Hence, let’s simply do this now:

```
source ${projectFolder}/Package-Builder/${osName}/install_swift_binaries.sh $projectFolder
```

3) In `build_package.sh`, we will also need these minor changes:

```
# Copy test credentials for project if available
if [ -e "${credentialsDir}" ]; then
   echo ">> Found folder with test credentials."
   # Copy test credentials over
   echo ">> copying ${credentialsDir} to ${projectBuildDir}"
   cp -RP ${credentialsDir}/* ${projectBuildDir}
else
   echo ">> No folder found with test credentials."
fi
```

I think that's it. I may have overlooked something; if you find that's the case, let's chat tomorrow and we will adjust the above accordingly.

**Comment by BDHernand** [comment]
@rolivieri lets chats about this once you get in.  BTW I ran Kitura-Couch DB against my branch and it worked fine with my new changes

**Comment by BDHernand** [comment]
@rolivieri put in the new changes.  Running Kitura-CouchDB against it now.  Mac on BluePic is failing... started the mac build again.  Looks like a collision or something.. code looks clean

**Comment by rolivieri** [comment]
@BDHernand Can you make sure we use the variable names defined above: 
`projectBuildDir`  and `credentialsDir`?  These new names match the new meaning we are now giving to these variables. Thanks.

**Pull request merged**
