### PR TITLE
Special swift

### PR DESCRIPTION
**Pull request by BDHernand**
Added new feature for custom builds

### CODE REVIEW

**Comment by BDHernand** [comment]
- [x] README updates
- [x] Renaming of test_special scripts (edited)
- [x] Use boolean for return code
- [x] Grab the swift command text from the file and execute that string (as opposed to executing the file itself)

**Comment by rolivieri** [comment]
@BDHernand 
- Validate if we need -f in addition to -s when checking for the custom compilation command
- Explore the possibility of using compound/complex if conditions in makefile: http://stackoverflow.com/questions/5584872/complex-conditions-check-in-makefile
- Explore using the equivalent of 'reflection' where once you determine the name of the platform where you the code is on, then the code simply uses that value (darwin vs linux) to look up the corresponding custom compile file.

**Comment by BDHernand** [comment]
ran a build on BlueSSLService pointing to my code and no .swift-build file and its working

**Comment by BDHernand** [comment]
-s FILE
      FILE exists and has a size greater than zero

**Pull request closed without merging**
