### PR TITLE
Issue 79

### PR DESCRIPTION
**Pull request by youming-lin**
IBM-Swift/Package-Builder#79

@christiancompton Please review

### CODE REVIEW

**Comment by christiancompton** [comment]
I tested Kitura-Starter against @youming-lin's fork, and the Linux build completed successfully:  https://travis-ci.org/IBM-Bluemix/Kitura-Starter/jobs/197448068

**Comment by youming-lin** [comment]
Currently seeing an issue with OSX, not sure where in the script it exited with a status of 1:
https://travis-ci.org/IBM-Swift/swift-html-entities/jobs/197427893

**Comment by christiancompton** [comment]
The Kitura-Starter OSX build with this fork completed successfully: https://travis-ci.org/IBM-Bluemix/Kitura-Starter/jobs/197448069

**Comment by youming-lin** [comment]
Mine failed again: https://travis-ci.org/IBM-Swift/swift-html-entities/jobs/197455781
One difference I see is that `Kitura-Starter` builds on Xcode8 whereas my build is on Xcode8.2.

I just tested locally and `swiftenv install` indeed returns error exit code if the toolchain is already installed:
```
ylin@youming-mbpr:~$ bash -c 'if swiftenv install 3.0.2 ; then echo "Success"; else echo "Failure"; fi'
3.0.2 is already installed.
Failure
```

**Comment by youming-lin** [comment]
OK, the latest commit should fix the issue now. Re-ran this same job and it's passing on both OSes.

**Comment by christiancompton** [comment]
I am in the process of wrapping up automated testing for Package-Builder, which I will use to process this.

This will close #https://github.com/IBM-Swift/DevOps/issues/92.

**Pull request merged**
