### PR TITLE
Add cfPush target to Makefile

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
Issue IBM-Swift/Kitura#798 - automating some checks before cf push.

### CODE REVIEW

**Comment by rolivieri** [comment]
@vadimeisenbergibm Thanks for the PR. I see what you are trying to do... but I am wondering... should this be automated? A few questions come to mind:
- Are you doing anything to prevent doing a `cf push` of a Swift package that is not meant to be pushed to the cloud? We have plenty of packages that fall under that category (mainly
  libraries). We’d like to have functionality in this repo that applies to any kind of Swift Packages (not only Swift packages that are apps). I guess you could check for the existence of an executable generated by the build process and that would be a cue… but that is not enough. Just the existence of an executable does not mean the app can be pushed to Bluemix. Only web server apps can pushed to Bluemix. Adding this `cfPush capability` may give the impression to users that they can push anything… just thinking out loud.
- How are you dealing with the case that a Swift Package may generate multiple executables? I guess you are just assuming the first executable is the one for the web server app? That may or may not be true… I don’t know how you could easily figure this out programmatically…
- What if there is not a `Profile` but there is a `manifest.yml` with the command attribute? It seems you'd need to take that into account if we are to provide this new functionality in the makefile.
- How are you handling the `PORT` number? If the Swift Package uses Swift-cfenv, then they are good… otherwise, this is completely app-specific. For these cases, you would need to pass the `PORT` environment variable as a runtime argument to the command to start the app… but I am not sure how you would determine how the PORT value should be passed since that is knowledge intrinsic to the app.
- What repos do you think will be leveraging this new functionality in this PR?

**Comment by vadimeisenbergibm** [comment]
@rolivieri 

> should this be automated?

My strong belief is that if anything can be automated, it should be automated. We should make the life of the users of Kitura@Bluemix as easy as possible. Our frameworks should try to make the best guess for the users if they do not specify something and should warn the users if something is missing/looks wrong.

We do not have to prevent each possible mistake, we should start with some automation and incrementally improve it.

> Are you doing anything to prevent doing a cf push of a Swift package that is not meant to be pushed to the cloud?

Yes, the script will not push a Swift package which is not executable. The script cannot prevent any possible mistake, however it is better than no automation at all.

> Only web server apps can pushed to Bluemix.

What do you mean? Any app written in Swift 3.0 that has Package.swift and runs on Ubuntu can be pushed to Bluemix.

> How are you dealing with the case that a Swift Package may generate multiple executables?

Good point. I have changed the script to handle this case. In case of multiple executables and no manifest - the script will not push. In case of Procfile, the script will check that the command matches a module with the same name.

> What if there is not a Profile but there is a manifest.yml with the command attribute?

Good point. I have changed the script to handle this.

> What repos do you think will be leveraging this new functionality in this PR?

Any repo that would use Package-Builder.

> How are you handling the PORT number? 

Good point. I will submit a proposal to integrate Kitura with Cloud Foundry out of the box, so the port issue will be handled.

**Comment by rolivieri** [comment]
@vadimeisenbergibm A few more comments:

I hear you, I am fan of automation too. :-) For this particular case, I am still trying to understand what real value we are adding with this new code. For instance, let’s go over the question about which repos you think will be leveraging this new functionality. Can you enumerate which ones specifically you have in mind? I am thinking that most (if not all) repos using Package Builder will not use this functionality (take BluePic for instance).

Also, I would prefer we encourage teams in our organization to have a manifest.yml file present with the corresponding attributes in it (especially since our apps serve as examples and best practices that other apps should follow). We don’t want customers thinking they don’t have to create these file artifacts (manifest.yml, etc.), push to Bluemix, and think everything is just going to work. Also, the moment a CF service is needed for the app, there is no option but to add the manifest.yml file to the repo (which will be the case for most apps).

If you have some specific use cases in mind, let's go over them. Maybe I just missing something that is obvious.

Also, not any app written in Swift 3.0 that has Package.swift and runs on Ubuntu can be pushed to Bluemix as a CF app. Instead, only web server apps written in Swift 3.0 that has Package.swift and runs on Ubuntu 14.04 can be pushed to Bluemix as a CF app. If you try to push any other kind of executables, it would fail since it is expecting the app to be listening on a given port to serve HTTP requests.

**Comment by vadimeisenbergibm** [comment]
@rolivieri 

> I am thinking that most (if not all) repos using Package Builder will not use this functionality 

Please note that both Kitura-Sample and Kitura-Starter-Bluemix use Package-Builder. The users of Kitura will probably start from these sample apps - copy them and then extend them. I am not talking about IBM-Swift team members/repos, I am talking about helping users of Kitura apps to push their apps to Bluemix.

>  We don’t want customers thinking they don’t have to create these file artifacts (manifest.yml, etc.), push to Bluemix, and think everything is just going to work.

But everything is going to work until you need a service - you can push your app without a manifest. Anyway, to separate the discussion into two parts, I removed pushing without manifest. Let's handle `make push` with manifest first.

The scenario I want to handle: a user starts a Kitura app from Kitura-Sample and then changes it according to Kitura-Starter-Bluemix, copying parts of it. The errors I want to prevent:
- The user forgets to create Procfile. The app is deployed but fails to start.
- The user forgets to create .cfignore file.  .build/Packages are deployed and cause problems during the build on the cloud
- The user creates an invalid Procfile. The app is deployed but fails to start.
- The user creates a valid Procfile, then renames his main module during refactoring, forgets to rename the command in Procfile. The app is deployed but fails to start.

If we can prevent these problems automatically - why should not we do it?  Actually, why swift_buildpack would not perform these checks on the cloud as well?

**Comment by rolivieri** [comment]
@vadimeisenbergibm A few points to continue the discussion before we can merge this PR:
- Kitura-Starter-Bluemix. I am aware we use Package-Builder (btw, only reason why I included it was for Travis CI purposes). Kitura-Starter-Bluemix has all the artifacts (e.g. manifest.yml) required for pushing to Bluemix… and it should, since we want folks to be aware of these file artifacts. If somebody forks this repo, they will have those artifacts with them, which is what we want. Hence, Kitura-Starter-Bluemix will never use the functionality in this PR. In the end, the **only required artifact** is the **manifest.yml**. Procfile is **not** required **if** `command` attribute is used in the manifest.yml. The .cfignore file won’t be required in the next release of the buildpack (see issue I opened several days ago: https://github.com/IBM-Swift/swift-buildpack/issues/34). The .cfignore file is a different beast and for this case we have already added code to deal with it not being present.
- Kitura-Sample - If this app is meant to be pushed to Bluemix, then we should add the required file artifacts (we **only** need a manifest.yml) and the app needs to be modified too. It needs to use Swift-cfenv, or a similar package, or it needs to take as input the PORT number. As it is right now, I don’t think you can push it to Bluemix… it should fail. Have you pushed Kitura-Sample as-is?
- Hence, I'd say that so far looks like we have no apps that will use the logic in this PR… and (see next points).
- Users/customers/developers need to know up front they need to have those files (instead of hiding the need for these files). Again, the **only** mandatory one is the **manifest.yml** file. Though it is certainly a best/recommended practice to have a .cfignore and .swift-version files as well. 
- We should have a manifest.yml file in all of our repos that are **meant** to be pushed to Bluemix. This also implies that none of our repos should be leveraging the logic in this PR.
- An app that has no dependencies on any other services does not provide much value. This brings us back to the following point: users will need to get familiar with the manifest.yml file no matter what. There is no way to hide this from developers; they will need to learn about this file.
- Re-emphasizing some of the points I mentioned before that are crucial to this conversation:
1. A Swift package can generate any number of executables… and only one of them could be the web server executable. This is a valid scenario and there is no way to know which is the right executable unless the developer specifies it somewhere (that’s why there is `command` attribute or a Procfile).
2. Even in the case that there is only one executable… how do you know how to run it? This is intrinsic knowledge of the app. Maybe the app uses Swift-cfenv, or the app uses another package similar to Swift-cfenv, or maybe the app just expects  runtime arguments. For instance, take a look at these possible commands:
- Server -bind 0.0.0.0:$PORT
- Server $PORT
- Server 
- Server --port=$PORT
- Server -portNumber=$PORT
- Server $PORT arg2 arg3
- Server arg1 arg2 $PORT $ENV_VAR2 arg3
  ... (etc.,  etc.)

Each one of those lines could be how the Swift app expects to be started. Again, this is intrinsic knowledge of the app.

**Comment by vadimeisenbergibm** [comment]
@rolivieri 
I would like to stress two points in my previous comment:

1.

> I removed pushing without manifest. Let's handle make push **with manifest** first.

2.

> The scenario I want to handle: a user starts a Kitura app from Kitura-Sample and then changes it according to Kitura-Starter-Bluemix, **copying** parts of it.

Let's focus on the scenario above. The points you raised in the previous comment are related to other scenarios - let's discuss them some other time. 

Kitura-Sample cannot be pushed to Bluemix as it is - I am talking about the scenario where users **copy** parts of Kitura-Sample, or extend Kitura-Sample to be pushed to Bluemix.

> The .cfignore file won’t be required in the next release of the buildpack (see issue I opened several days ago: IBM-Swift/swift-buildpack#34 

This is good! It still would be nice to warn the user about lack of .cfignore and warn about unnecessary pushing of .build and Packages.

**Comment by rolivieri** [comment]
@vadimeisenbergibm - Summarizing the points in this discussion so far:
- The buildpack cannot warn the developer about the .cfignore file not being present in the repo. .cfignore is a Cloud Foundry artifact used by the CLI… (it is not specific to the Swift buildpack). The .cfignore  file never is never uploaded (hence, the buildpack cannot know if it’s there or not). The builpack could warn the developer that he/she is pushing the .build and/or Packages folder… but I don’t see the need for that right now since we remove those folders to avoid issues/problems. Also, we want the buildpack to execute as fast as possible and avoid the need for any additional checks that are not really necessary.
- Thanks for confirming that Kitura-Sample cannot be pushed to Bluemix as it is. We have then confirmed that we have no repos that would leverage the functionality in this PR and we, as discussed before, we don’t want customers thinking they don’t have to create these file artifacts (manifest.yml) to push to Bluemix.
- A Swift repo to be pushed to Bluemix must provide a manifest.yml file that includes the specific command for starting the app (as discussed in my previous message above) along with any other required fields. Hiding the need for the file will be counterproductive to users/developers.
- If a user starts from Kitura-Sample, as we discussed, they will need to make several changes manually to make it ready for Bluemix (unless you or the Kitura team updates that app). This PR is not addressing those changes (and it should not). 
- If a user starts from Kitura-Starter-Bluemix, they’ll have everything they need since the app is deployable to Bluemix as-is. 
- Given the points above, can we close this PR or do you still see the need for merging? If the latter, let’s discuss further since I may missing something that you are seeing.

**Comment by vadimeisenbergibm** [comment]
Closing this PR until design discussion on it is completed.

**Pull request closed without merging**
