### PR TITLE
Podspecs automatic generation

### PR DESCRIPTION
**Pull request by ShihabMehboob**
This PR aims to automatically generate Podspecs for any repo that uses a 'POD_ELIGIBLE' tag in their .travis configuration, and uploading the Pod to the spec for public visibility and usage.

### CODE REVIEW

**Comment by ianpartridge** [comment]
Thanks - can you run this through https://www.shellcheck.net/ and fix any issues?

**Comment by djones6** [comment]
@ShihabMehboob can you link to a successful Travis job which used this script? It looks plausible, but as I'm not that familiar with the process of publishing pods, I'd feel better seeing a working example.

**Comment by ShihabMehboob** [comment]
A test branch has been created on Package-Builder: https://github.com/ShihabMehboob/Package-Builder/tree/testpods

And a test on Kitura-net that makes use of it: https://github.com/IBM-Swift/Kitura-net/pull/279

The test branch on Package-Builder may have to be merged first to work though.

**Review by djones6 — COMMENTED** [review]
I don't understand why we would automate the _generation_ of the podspec file itself.  There are various details that should be (carefully) hand crafted in this file for each repo - such as the description, module name, source locations etc.  I don't think coding these into Travis env vars for the sake of being able to auto-generate the whole file is a workable approach: it means an admin has to do work on each repo, and it's opaque to non-admins.

I'd rather we hand-craft the podspec, but automate our release process to include updating the tag information and publishing the pod.  Perhaps this would help?
https://fuller.li/posts/automated-cocoapods-releases-with-ci/

**Comment by djones6** [comment]
Closing this PR as it is not the direction we want to take.  @Andrew-Lees11 will take a look at our options for automating publishing.

**Pull request closed without merging**
