### PR TITLE
Generate and print backtraces on swift test crash to help debug the root cause

### PR DESCRIPTION
**Pull request by na-gupta**
Generate and print backtraces on swift test crash to help debug the root cause

### CODE REVIEW

**Comment by rolivieri** [comment]
Hello @na-gupta - 

1) Can you move this new logic to a separate file that we can then source from build_package.sh? Maybe you name it `run_tests.sh` or `execute_tests.sh` (something along those lines)?

2) Can you move line 142 to the line right after line 121? Or are you expecting anything in that new block to fail?

3) This seems to assume a given suffix for the module getting tested: `*PackageTests.xctest`? Would this following suffix work instead: `*Tests.xctest`? We have modules that do not end in `PackageTests.xctest`.

4) Can you rename the `core` variable to `coreFile` (or something similar)?

**Comment by na-gupta** [comment]
@rolivieri  Addressed 1,3 and 4.

For 2, I did it this way because I did not want any failures/errors in the core handling block to cause the script to exit, but can change it if you still want to.

**Comment by rolivieri** [comment]
@na-gupta Thanks. One more question, with these changes, what happens to the status of the build if any of the test cases fail? We still need to build to be marked as failure under such scenario after you collect/display the core dump. Since we are executing `set -e` after evaluating the value of `TEST_EXIT_CODE`, would that mean that the build will be labeled as successful even if a test failed? Maybe I missed something.

**Comment by na-gupta** [comment]
Line 26 of run_tests.sh - `exit $TEST_EXIT_CODE` - causes the script to exit with the exit code for `swift test` whenever the exit code is non-zero.

**Comment by rolivieri** [comment]
@na-gupta Got it, I overlooked that. Sorry one more thing, can you do this PR against develop? We now have a develop branch where we merge all PRs.

**Comment by na-gupta** [comment]
@rolivieri Done. Thanks!

**Pull request merged**
